import type { Mission, Bug, TestEnvState } from "../types";

export const INITIAL_ENV: () => TestEnvState = () => ({
  username: "", password: "", loggedIn: false, otp: "", resetEmail: "",
  otpUsed: false, loginAttempts: 0,
  searchQuery: "", cart: [], coupon: "", couponApplied: false,
  address: "", paymentMethod: "", orderPlaced: false, wishlist: [],
  balance: 5000, transferTo: "", transferAmount: 0,
  depositAmount: 0, withdrawAmount: 0,
  transactions: [], txIdCounter: 1,
  selectedSeat: null, bookedSeats: [], cancelledSeat: null,
  viewport: "desktop", consoleOpen: false, consoleInput: "",
  consoleOutput: [], networkLog: [],
});

export const LOGIN_BUGS: Bug[] = [
  {
    id: "login-01", title: "Login succeeds with empty username",
    description: "The system allows login when username is left blank.",
    severity: "high", priority: "P1", category: "Validation",
    technique: "Boundary Value Analysis",
    hints: ["What happens when fields are empty?", "Try logging in without a username."],
    xpReward: 100,
  },
  {
    id: "login-02", title: "Login succeeds with empty password",
    description: "The system allows login when password is left blank.",
    severity: "critical", priority: "P1", category: "Security",
    technique: "Exploratory Testing",
    hints: ["Have you tried logging in without a password?", "Security is about checking what's missing."],
    xpReward: 200,
  },
  {
    id: "login-03", title: "Password field accepts spaces",
    description: "Password validation allows a password of only spaces.",
    severity: "medium", priority: "P2", category: "Validation",
    technique: "Equivalence Partitioning",
    hints: ["What constitutes a 'real' password?", "Try whitespace-only input."],
    xpReward: 60,
  },
  {
    id: "login-04", title: "No rate limiting on login attempts",
    description: "Unlimited login attempts without lockout or delay.",
    severity: "high", priority: "P2", category: "Security",
    technique: "Functional Testing",
    hints: ["Try logging in many times in a row.", "How many attempts can you make?"]
      ,
    xpReward: 120,
  },
  {
    id: "login-05", title: "OTP can be reused after reset",
    description: "After using the OTP for password reset, the same OTP still works.",
    severity: "critical", priority: "P1", category: "Security",
    technique: "State Testing",
    hints: ["Reset the password using the OTP. What happens if you try the OTP again?"],
    xpReward: 180,
  },
  {
    id: "login-06", title: "Password reset email has no validation",
    description: "Password reset accepts any string, including invalid emails.",
    severity: "low", priority: "P3", category: "Validation",
    technique: "Input Validation",
    hints: ["What happens if you type a random string in the reset email field?"],
    xpReward: 40,
  },
];

export const ECOMMERCE_BUGS: Bug[] = [
  {
    id: "ecom-01", title: "Cart quantity can be set to negative",
    description: "Users can set product quantity to negative values, resulting in negative totals.",
    severity: "high", priority: "P1", category: "Functional",
    technique: "Boundary Value Analysis",
    hints: ["Try setting the cart quantity to 0 or a negative number.", "What happens at the edges?"],
    xpReward: 100,
  },
  {
    id: "ecom-02", title: "Coupon can be applied multiple times",
    description: "The same coupon code can be applied repeatedly, stacking discounts indefinitely.",
    severity: "high", priority: "P2", category: "Logic",
    technique: "Exploratory Testing",
    hints: ["Apply the coupon once. Then try applying it again.", "What happens to the discount?"],
    xpReward: 120,
  },
  {
    id: "ecom-03", title: "Product price changes at checkout",
    description: "The total is calculated incorrectly when items are in cart.",
    severity: "critical", priority: "P1", category: "Functional",
    technique: "Functional Testing",
    hints: ["Add items to cart and check the total carefully.", "Does the math add up?"],
    xpReward: 180,
  },
  {
    id: "ecom-04", title: "Empty address allows order placement",
    description: "Users can place orders without providing a shipping address.",
    severity: "medium", priority: "P2", category: "Validation",
    technique: "Input Validation",
    hints: ["Try placing an order without entering an address."],
    xpReward: 80,
  },
  {
    id: "ecom-05", title: "Wishlist items not persisted",
    description: "Items added to wishlist disappear when searching.",
    severity: "low", priority: "P4", category: "State",
    technique: "State Testing",
    hints: ["Add something to wishlist, then try searching. What happens?"],
    xpReward: 50,
  },
  {
    id: "ecom-06", title: "Quantity 99999 causes overflow in total",
    description: "Very large quantities produce incorrect or negative totals due to integer overflow.",
    severity: "high", priority: "P2", category: "Boundary",
    technique: "Boundary Value Analysis",
    hints: ["What happens with extremely large quantities?"],
    xpReward: 140,
  },
];

export const BANKING_BUGS: Bug[] = [
  {
    id: "bank-01", title: "Transfer allows negative amount",
    description: "Negative transfer amounts are accepted, effectively depositing money.",
    severity: "critical", priority: "P1", category: "Security",
    technique: "Boundary Value Analysis",
    hints: ["What happens if you transfer a negative amount?"],
    xpReward: 200,
  },
  {
    id: "bank-02", title: "Transfer exceeds balance",
    description: "User can transfer more than their current balance.",
    severity: "critical", priority: "P1", category: "Security",
    technique: "Functional Testing",
    hints: ["Try transferring more than your current balance."],
    xpReward: 180,
  },
  {
    id: "bank-03", title: "Transaction history shows wrong balance",
    description: "After a transfer, the transaction list shows incorrect balance.",
    severity: "high", priority: "P2", category: "State",
    technique: "State Testing",
    hints: ["Check your transaction history after a transfer. Does it look right?"],
    xpReward: 120,
  },
  {
    id: "bank-04", title: "Decimal amount not handled correctly",
    description: "Deposits with decimal amounts are rounded down.",
    severity: "medium", priority: "P2", category: "Functional",
    technique: "Equivalence Partitioning",
    hints: ["Try depositing $99.99. What actually gets added?"],
    xpReward: 90,
  },
  {
    id: "bank-05", title: "Transfer to empty account accepted",
    description: "System accepts transfer with no destination account specified.",
    severity: "high", priority: "P1", category: "Validation",
    technique: "Input Validation",
    hints: ["Try sending a transfer without entering an account number."],
    xpReward: 110,
  },
  {
    id: "bank-06", title: "Duplicate transaction on double-click",
    description: "Clicking deposit or transfer twice creates two identical transactions.",
    severity: "medium", priority: "P3", category: "State",
    technique: "Exploratory Testing",
    hints: ["What happens if you click deposit really fast twice?"],
    xpReward: 80,
  },
];

export const ALL_MISSIONS: Mission[] = [
  {
    id: "login", title: "Authentication System", icon: "🔐",
    difficulty: 1,
    description: "Test the login, registration, OTP, and password reset flow of a new authentication system. Look for validation bypasses, security gaps, and state-related bugs.",
    clientName: "SecureAuth Corp", sprintName: "Sprint 14",
    timeLimit: 600, bugs: LOGIN_BUGS,
    requirements: [
      "Password must contain at least 8 characters",
      "Username cannot be empty",
      "OTP should be single-use only",
      "Login should lock after 10 failed attempts",
    ],
  },
  {
    id: "ecommerce", title: "E-Commerce System", icon: "🛒",
    difficulty: 2,
    description: "Test a brand-new online store — product search, cart management, coupon codes, checkout, and payment flow. Focus on pricing accuracy and business logic.",
    clientName: "ShopWave Inc", sprintName: "Sprint 22",
    timeLimit: 720, bugs: ECOMMERCE_BUGS,
    requirements: [
      "Cart quantity must be 1 or greater",
      "Coupon 'SAVE10' gives 10% off, applied only once",
      "Shipping address is required for checkout",
      "Total must equal sum of (price × quantity) minus discounts",
    ],
  },
  {
    id: "banking", title: "Banking Application", icon: "🏦",
    difficulty: 3,
    description: "Test a digital banking platform — transfers, deposits, withdrawals, and transaction history. Security and accuracy are paramount. No room for error here.",
    clientName: "NeoBank Ltd", sprintName: "Sprint 8",
    timeLimit: 900, bugs: BANKING_BUGS,
    requirements: [
      "Transfer amount must be positive",
      "Transfer cannot exceed available balance",
      "Transaction history must reflect accurate balances",
      "Decimal amounts must be preserved to 2 decimal places",
    ],
  },
];
